language: node_js
node_js:
- '0.12'
before_script:
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.email "ligeek49@gmail.com"
- git config --global user.name "Jinyoung Kim (via TravisCI)"
- npm install -g bower grunt-cli
- gem install sass
- bower install
services: mongodb
before_install:
- openssl aes-256-cbc -K $encrypted_c9d3d02509c8_key -iv $encrypted_c9d3d02509c8_iv
  -in encrypt.tar.enc -out encrypt.tar -d
- tar xvf encrypt.tar
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - grunt deploy
